/**
 * Generates src/environments/environment.generated.ts from environment
 * variables or a local .env file, so secrets never live in source control.
 *
 * Resolution order: process.env (CI/Cloudflare) first, then frontend/.env.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envFilePath = resolve(projectRoot, '.env');
const outputPath = resolve(projectRoot, 'src', 'environments', 'environment.generated.ts');

function parseEnvFile(path) {
  const vars = {};
  if (!existsSync(path)) {
    return vars;
  }
  for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex === -1) {
      continue;
    }
    const key = trimmed.slice(0, separatorIndex).trim();
    let value = trimmed.slice(separatorIndex + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

const fileVars = parseEnvFile(envFilePath);
const accessKey = process.env['VITE_WEB3FORMS_ACCESS_KEY'] ?? fileVars['VITE_WEB3FORMS_ACCESS_KEY'];

if (!accessKey) {
  console.error(
    '\n[generate-env] Missing VITE_WEB3FORMS_ACCESS_KEY.\n' +
      'Set it as an environment variable (the hosting build provides it in production),\n' +
      'or copy frontend/.env.example to frontend/.env and fill it in for local development.\n'
  );
  process.exit(1);
}

const contents = `// AUTO-GENERATED by scripts/generate-env.mjs — do not edit or commit.
export const web3formsAccessKey = '${accessKey.replace(/'/g, "\\'")}';
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, contents, 'utf8');
console.log('[generate-env] Wrote src/environments/environment.generated.ts');
